CUDA_VISIBLE_DEVICES=0,1,2,3 \
python ../finetune_llama3_imlor2c.py \
  --model_name_or_path "LLM-Research/Meta-Llama-3___1-8B/" \
  --data_path ""yahma/alpaca-cleaned"" \
  --bf16 True \
  --output_dir "outputs/llama3.1_8B_Base_Finetune" \
  --num_train_epochs 4 \
  --per_device_train_batch_size 4 \
  --gradient_accumulation_steps 2 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 2000 \
  --save_total_limit 1 \
  --learning_rate 1e-4 \
  --weight_decay 0.0 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 10 \
  --report_to "none" \
  --model_max_length 1024 \
  --gradient_checkpointing False \
  --lazy_preprocess True \
  --use_lor2c
